# Generated by Django 5.0.1 on 2024-02-11 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Music Name')),
                ('category', models.CharField(max_length=120, verbose_name='Category')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
