# Generated by Django 5.0.1 on 2024-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0002_alter_music_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='removed_for_representation',
            field=models.BooleanField(default=False),
        ),
    ]
