# Generated by Django 5.0.1 on 2024-02-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_blog', '0003_music_removed_for_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='removed_for_representation',
            field=models.BooleanField(default=True),
        ),
    ]
